# Dogs

In [1]:
# For neural networks.
import keras as kr
# For data frames.
import pandas as pd
# For numerical arrays.
import numpy as np
# For preprocessing data.
import sklearn.preprocessing as pre
# For splitting data sets.
import sklearn.model_selection as mod
# For whitening.
import sklearn.decomposition as dec

Using TensorFlow backend.


## Preparing

In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/ianmcloughlin/datasets/master/dogs.csv")
df

pure  age  weight  height  lifespan
0    True    3    7.94    49.6        15
1    True    7    5.05    63.5        17
2    True    6   16.15    68.2        11
3   False    3   15.50    64.7        12
4   False    3   12.17    59.7        14
..    ...  ...     ...     ...       ...
95  False    4   20.76    52.2        10
96  False    4   17.40    47.5        11
97  False    6   15.60    51.4        12
98  False    3    8.37    54.1        16
99   True    7    9.09    50.3        14

[100 rows x 5 columns]

In [3]:
pureenc = pre.LabelBinarizer()
pureenc.fit(df['pure'])
df['pureenc'] = pureenc.transform(df['pure'])

In [4]:
x = df[['pureenc', 'age', 'weight', 'height']]
y = df['lifespan']

In [5]:
x

pureenc  age  weight  height
0         1    3    7.94    49.6
1         1    7    5.05    63.5
2         1    6   16.15    68.2
3         0    3   15.50    64.7
4         0    3   12.17    59.7
..      ...  ...     ...     ...
95        0    4   20.76    52.2
96        0    4   17.40    47.5
97        0    6   15.60    51.4
98        0    3    8.37    54.1
99        1    7    9.09    50.3

[100 rows x 4 columns]

In [6]:
y

0     15
1     17
2     11
3     12
4     14
      ..
95    10
96    11
97    12
98    16
99    14
Name: lifespan, Length: 100, dtype: int64

In [7]:
x_train, x_test, y_train, y_test = mod.train_test_split(x, y, test_size=0.3)

## Building and training

In [8]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [9]:
m.fit(x_train, y_train, epochs=100, batch_size=10)



Epoch 1/100
70/70 [==============================] - 1s 20ms/step - loss: 82.2761
Epoch 2/100
70/70 [==============================] - 0s 692us/step - loss: 67.1725
Epoch 3/100
70/70 [==============================] - 0s 422us/step - loss: 53.3654
Epoch 4/100
70/70 [==============================] - 0s 289us/step - loss: 41.6396
Epoch 5/100
70/70 [==============================] - 0s 946us/step - loss: 31.3539
Epoch 6/100
70/70 [==============================] - 0s 522us/step - loss: 23.0326
Epoch 7/100
70/70 [==============================] - 0s 357us/step - loss: 17.3949
Epoch 8/100
70/70 [==============================] - 0s 557us/step - loss: 13.7291
Epoch 9/100
70/70 [==============================] - 0s 390us/step - loss: 11.4647
Epoch 10/100
70/70 [==============================] - 0s 576us/step - loss: 10.7647
Epoch 11/100
70/70 [==============================] - ETA: 0s - loss: 10.29 - 0s 667us/step - loss: 10.5220
Epoch 12/100
70/70 [==============================] - 0s 435

70/70 [==============================] - 0s 248us/step - loss: 8.2692
Epoch 95/100
70/70 [==============================] - 0s 499us/step - loss: 8.2066
Epoch 96/100
70/70 [==============================] - 0s 833us/step - loss: 8.2100
Epoch 97/100
70/70 [==============================] - 0s 208us/step - loss: 8.1870
Epoch 98/100
70/70 [==============================] - 0s 426us/step - loss: 8.2335
Epoch 99/100
70/70 [==============================] - 0s 264us/step - loss: 8.2002
Epoch 100/100
70/70 [==============================] - 0s 256us/step - loss: 8.2091


In [10]:
m.predict(x_test).round().T

array([[11., 11., 12.,  8., 12., 10.,  9.,  8., 11., 16.,  9.,  8., 13.,
        16., 13., 13., 14., 13., 13., 12., 11., 13., 14., 18., 11., 12.,
         9., 10., 12., 12.]], dtype=float32)

In [11]:
y_test.as_matrix().astype(np.float32)

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([11., 10., 18., 12., 10., 11., 11.,  9., 12., 13., 15., 10., 14.,
       17., 19., 15., 10., 16., 14., 10., 14., 12., 16., 17., 12., 16.,
       10., 16., 15., 11.], dtype=float32)

In [12]:
m.evaluate(x_test, y_test)

30/30 [==============================] - 0s 5ms/step


8.581741333007812

## Scaling

In [13]:
scaler = pre.StandardScaler()
scaler.fit(x_train)
x_train_scaled = scaler.transform(x_train)

In [14]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(20, input_dim=4, activation="relu"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [15]:
m.fit(x_train_scaled, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 1s 13ms/step - loss: 163.2016
Epoch 2/100
70/70 [==============================] - 0s 427us/step - loss: 161.3515
Epoch 3/100
70/70 [==============================] - 0s 218us/step - loss: 159.5960
Epoch 4/100
70/70 [==============================] - 0s 318us/step - loss: 157.8161
Epoch 5/100
70/70 [==============================] - 0s 395us/step - loss: 156.0170
Epoch 6/100
70/70 [==============================] - 0s 237us/step - loss: 154.2581
Epoch 7/100
70/70 [==============================] - 0s 209us/step - loss: 152.4640
Epoch 8/100
70/70 [==============================] - 0s 229us/step - loss: 150.7070
Epoch 9/100
70/70 [==============================] - 0s 271us/step - loss: 149.0008
Epoch 10/100
70/70 [==============================] - 0s 229us/step - loss: 147.2024
Epoch 11/100
70/70 [==============================] - 0s 176us/step - loss: 145.4305
Epoch 12/100
70/70 [==============================] - 0s 319us/step - loss:

70/70 [==============================] - 0s 440us/step - loss: 9.6727
Epoch 98/100
70/70 [==============================] - 0s 391us/step - loss: 9.2124
Epoch 99/100
70/70 [==============================] - 0s 471us/step - loss: 8.7634
Epoch 100/100
70/70 [==============================] - 0s 264us/step - loss: 8.3478


In [16]:
x_test_scaled = scaler.transform(x_test)
m.predict(x_test_scaled).round().T

array([[ 9.,  8., 17., 12., 12.,  8., 13.,  6.,  9., 13., 15.,  9., 12.,
        13., 17., 16., 11., 12., 11.,  9., 14., 10., 10., 13.,  7., 15.,
         8., 16., 13.,  6.]], dtype=float32)

In [17]:
y_test.as_matrix().astype(np.float32)

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([11., 10., 18., 12., 10., 11., 11.,  9., 12., 13., 15., 10., 14.,
       17., 19., 15., 10., 16., 14., 10., 14., 12., 16., 17., 12., 16.,
       10., 16., 15., 11.], dtype=float32)

In [18]:
m.evaluate(x_test_scaled, y_test)

30/30 [==============================] - 0s 3ms/step


7.1724853515625

## Whitening

In [19]:
pca = dec.PCA(n_components=4, whiten=True)
pca.fit(x_train)
x_train_white = pd.DataFrame(pca.transform(x_train), columns=x.columns)
x_train_white

pureenc       age    weight    height
0   0.351231 -0.023006 -1.079929 -0.951374
1  -0.012764 -1.157900 -1.195173 -1.064293
2   0.941085  0.359779 -0.967660 -0.936212
3   0.743577 -1.088204 -0.515159 -1.113794
4  -0.611093  2.285833 -0.555464 -0.658486
..       ...       ...       ...       ...
65  0.894656 -1.621427 -0.512884  0.820352
66  0.197414 -0.899546 -0.027932  0.917350
67 -1.524036 -0.242519 -0.828242 -0.905044
68 -1.895772 -0.433372  0.782178  1.032982
69 -0.156841 -0.437033  1.055249  0.947214

[70 rows x 4 columns]

In [20]:
m = kr.models.Sequential()

m.add(kr.layers.Dense(100, input_dim=4, activation="tanh"))
m.add(kr.layers.Dense(1, activation="linear"))

m.compile(loss="mean_squared_error", optimizer="adam")

In [21]:
m.fit(x_train_white, y_train, epochs=100, batch_size=10)

Epoch 1/100
70/70 [==============================] - 1s 11ms/step - loss: 153.6590
Epoch 2/100
70/70 [==============================] - 0s 267us/step - loss: 151.0955
Epoch 3/100
70/70 [==============================] - 0s 292us/step - loss: 148.5965
Epoch 4/100
70/70 [==============================] - 0s 266us/step - loss: 146.1226
Epoch 5/100
70/70 [==============================] - 0s 179us/step - loss: 143.5247
Epoch 6/100
70/70 [==============================] - 0s 341us/step - loss: 141.0165
Epoch 7/100
70/70 [==============================] - 0s 271us/step - loss: 138.2976
Epoch 8/100
70/70 [==============================] - 0s 253us/step - loss: 135.4856
Epoch 9/100
70/70 [==============================] - 0s 147us/step - loss: 132.6652
Epoch 10/100
70/70 [==============================] - 0s 286us/step - loss: 129.5296
Epoch 11/100
70/70 [==============================] - 0s 334us/step - loss: 126.3123
Epoch 12/100
70/70 [==============================] - 0s 201us/step - loss:

70/70 [==============================] - 0s 402us/step - loss: 0.2212
Epoch 100/100
70/70 [==============================] - 0s 416us/step - loss: 0.2211


In [22]:
x_test_white = scaler.transform(x_test)
m.predict(x_test_white).round().T

array([[14., 12.,  7., 10., 17., 13., 18., 12., 11., 14., 14., 17.,  7.,
        14., 13., 17., 14., 13., 16., 10., 16.,  6.,  9., 14., 12., 10.,
        10., 11., 15.,  9.]], dtype=float32)

In [23]:
y_test.as_matrix().astype(np.float32)

C:\Users\mclou\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


array([11., 10., 18., 12., 10., 11., 11.,  9., 12., 13., 15., 10., 14.,
       17., 19., 15., 10., 16., 14., 10., 14., 12., 16., 17., 12., 16.,
       10., 16., 15., 11.], dtype=float32)

In [24]:
m.evaluate(x_test_white, y_test)

30/30 [==============================] - 1s 32ms/step


19.537107467651367

## End